name: Update List

on:
  workflow_dispatch: # para dispararlo manualmente
  schedule:
    - cron: "0 3 * * *"  # se ejecuta diario a las 3am

jobs:
  update_file:
    runs-on: ubuntu-latest
    #permissions:
    #  contents: write
    steps:
      - uses: actions/checkout@v4
      - run: wget -O maluma.m3u https://ipfs.io/ipns/k2k4r8oqlcjxsritt5mczkcn4mmvcmymbqw7113fz2flkrerfwfps004/data/listas/lista_fuera_iptv.m3u
      - run: wget -O ozuna.m3u https://ipfs.io/ipns/k2k4r8oqlcjxsritt5mczkcn4mmvcmymbqw7113fz2flkrerfwfps004/data/listas/lista_iptv.m3u
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add archivo.txt
          git commit -m "Auto actualizacion archivo"
          git push
