name: Docker Build y Run

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Run List Updater
        uses: pocholo30/yandel@main
