name: Docker Build y Run

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
      
      - name: Construir la imagen de Docker
        run: docker build -t zn-test .
      
      - name: Ejecutar el contenedor
        run: docker run zn-test
